### ISSUE TITLE
Noob-Unfriendly Instructions in the Readme

### ISSUE THREAD

**Issue by RubinXnibu** [sparkfun/Qwiic_Py#13]
The repository readme has confusing instructions for beginners:
(1) It lists how to use git to clone the repository and then lists how to use pypi but really should say only one is necessary, and should start with pypi, as it's easier for beginners, list the advanced self-install method second.
(2) Insert blurbs with instructions tailored for dependencies for your three target hardware platforms.  With a raspberry pi flashed with a new raspian OS in 2021, pip is not installed and neither is setup-tools, breaking both the pip and the python setup.py install instructions.   I don't have the other two platforms so I cannot volunteer to update the instructions for those, but I volunteer to flesh out the RPi instructions.
(3) A "What To Do Next" section needs to be added for beginners -- I bought my first shiny new Qwiic item, I've hooked it up, enabled I2C in the OS and saw the /dev/i2c* device created, I installed qwiic_py ... now what?  If this is covered elsewhere, at least have links to those elsewheres.
(4) Mention that this package works with both python2 and python3 and if one recommended over the other because of legacy code?   Since beginners are new to github, they might not know to look for the "python" icons.
(5) The "Read The Docs" is mostly a copy-paste of the README.  It should really go into further detail because when beginners get stuck they'll need more hand-holding.

**Comment by santaimpersonator** [comment]
There was an example script, but the `list_devices()` method is currently broken (see issue #2) and I commented it out due to the amount of duplicate issues filed over it. I am in the middle of an update right now and pending testing, I will make sure to re-display the example.

That being said, you should be following the hookup guide for your device (if a Python package is available). For example, the MAX30101 photodetector has a Python package and information can be found in this [section of the hookup guide](https://learn.sparkfun.com/tutorials/sparkfun-photodetector-max30101-hookup-guide/python-package). Further information on the implementation of the Python package, is documented on the [ReadtheDocs](https://qwiic-max3010x-py.readthedocs.io/en/latest/index.html). Please note, some of the newer packages don't have a ReadtheDocs page (invalid address) due to an issue on the ReadtheDocs' implementation (we have no control over it). However, you can still find examples and information of the device's Python package repo.

This package primarily implements the installation of all available Python packages; there really is no other functionality until I finalize my update to fix the broken method.

Please subscribe to issue #2. Once, I close the issue, the update will become available again. I will be closing this issue in the meantime, since it is tied to that issue.
